version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgres://user:password@db:5432/company_db?sslmode=disable
      - SERVER_ADDRESS=:8080
      - JWT_SECRET=your-secret-key-change-me
      - LOG_LEVEL=info

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: company_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d company_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: